/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.oppo.mobaddemo;

public final class R {
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int layoutManager=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int reverseLayout=0x7f010002;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int spanCount=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int stackFromEnd=0x7f010003;
    }
    public static final class color {
        public static final int action_bn_text_color=0x7f070000;
        public static final int colorAccent=0x7f070001;
        public static final int colorPrimary=0x7f070002;
        public static final int colorPrimaryDark=0x7f070003;
        public static final int desc_color=0x7f070004;
        public static final int title_color=0x7f070005;
    }
    public static final class dimen {
        public static final int action_bn_size=0x7f080000;
        public static final int desc_size=0x7f080001;
        public static final int item_touch_helper_max_drag_scroll_per_frame=0x7f080002;
        public static final int item_touch_helper_swipe_escape_max_velocity=0x7f080003;
        public static final int item_touch_helper_swipe_escape_velocity=0x7f080004;
        public static final int title_size=0x7f080005;
    }
    public static final class drawable {
        public static final int leak_canary_icon=0x7f020000;
        public static final int leak_canary_notification=0x7f020001;
        public static final int leak_canary_toast_background=0x7f020002;
        public static final int oppo_native_512_512_bg_img=0x7f020003;
        public static final int oppo_native_click_bn_normal_bg_img=0x7f020004;
        public static final int oppo_native_click_bn_pressed_bg_img=0x7f020005;
        public static final int oppo_native_click_bn_selector=0x7f020006;
        public static final int oppo_native_close_bn_bg_img=0x7f020007;
        public static final int oppo_native_logo_img=0x7f020008;
        public static final int oppo_native_one_bg_img=0x7f020009;
        public static final int oppo_reward_video_play_bn_img=0x7f02000a;
    }
    public static final class id {
        public static final int action_bn=0x7f09001c;
        public static final int ad_container=0x7f090001;
        public static final int ad_rv=0x7f090027;
        public static final int banner_bn=0x7f090005;
        public static final int click_bn=0x7f090018;
        public static final int close_iv=0x7f090016;
        public static final int desc_tv=0x7f090011;
        public static final int destroy_ad_bn=0x7f090003;
        public static final int height_et=0x7f090026;
        public static final int height_tv=0x7f090025;
        public static final int icon_iv=0x7f09001b;
        public static final int img_1_iv=0x7f090012;
        public static final int img_2_iv=0x7f090013;
        public static final int img_3_iv=0x7f090014;
        public static final int img_iv=0x7f090028;
        public static final int interstitial_bn=0x7f090006;
        public static final int item_touch_helper_previous_elevation=0x7f090000;
        public static final int leak_canary_action=0x7f09002f;
        public static final int leak_canary_display_leak_failure=0x7f09002e;
        public static final int leak_canary_display_leak_list=0x7f09002d;
        public static final int leak_canary_row_connector=0x7f090032;
        public static final int leak_canary_row_more=0x7f090033;
        public static final int leak_canary_row_text=0x7f090030;
        public static final int leak_canary_row_time=0x7f090031;
        public static final int load_ad_bn=0x7f090002;
        public static final int load_native_ad_bn=0x7f090019;
        public static final int logo_iv=0x7f090015;
        public static final int mix_bn=0x7f09000a;
        public static final int native_320X210_text_img_bn=0x7f09000d;
        public static final int native_512X512_text_icon_bn=0x7f09000b;
        public static final int native_640X320_text_img_bn=0x7f09000c;
        public static final int native_ad_container=0x7f09000f;
        public static final int native_bn=0x7f090007;
        public static final int native_group_320X210_text_img_bn=0x7f09000e;
        public static final int native_temple_320X210_normal_bn=0x7f09001e;
        public static final int native_temple_320X210_recycler_bn=0x7f090021;
        public static final int native_temple_640X320_normal_bn=0x7f09001d;
        public static final int native_temple_640X320_recycler_bn=0x7f090020;
        public static final int native_temple_group_320X210_normal_bn=0x7f09001f;
        public static final int native_temple_group_320X210_recycler_bn=0x7f090022;
        public static final int native_templet_bn=0x7f090008;
        public static final int native_templet_item_ad_container=0x7f09002b;
        public static final int native_templet_item_title_tv=0x7f09002c;
        public static final int req_video_ad=0x7f090029;
        public static final int reward_video_bn=0x7f090009;
        public static final int show_ad_bn=0x7f090004;
        public static final int show_native_ad_bn=0x7f09001a;
        public static final int status_tv=0x7f09002a;
        public static final int title_tv=0x7f090017;
        public static final int top_rl=0x7f090010;
        public static final int width_et=0x7f090024;
        public static final int width_tv=0x7f090023;
    }
    public static final class layout {
        public static final int activity_banner=0x7f040000;
        public static final int activity_interstitial=0x7f040001;
        public static final int activity_main=0x7f040002;
        public static final int activity_mix=0x7f040003;
        public static final int activity_native=0x7f040004;
        public static final int activity_native_group_text_img_320_210=0x7f040005;
        public static final int activity_native_one=0x7f040006;
        public static final int activity_native_templet=0x7f040007;
        public static final int activity_native_templet_normal=0x7f040008;
        public static final int activity_native_templet_recycler_view=0x7f040009;
        public static final int activity_native_text_icon_512_512=0x7f04000a;
        public static final int activity_native_text_img_320_210=0x7f04000b;
        public static final int activity_native_text_img_640_320=0x7f04000c;
        public static final int activity_reward_video=0x7f04000d;
        public static final int activity_splash=0x7f04000e;
        public static final int item_native_templet_ad=0x7f04000f;
        public static final int item_native_templet_data=0x7f040010;
        public static final int leak_canary_display_leak=0x7f040011;
        public static final int leak_canary_heap_dump_toast=0x7f040012;
        public static final int leak_canary_leak_row=0x7f040013;
        public static final int leak_canary_ref_row=0x7f040014;
        public static final int leak_canary_ref_top_row=0x7f040015;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
        public static final int ic_launcher_round=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f050018;
        public static final int banner_bn=0x7f050019;
        public static final int destroy_ad_bn=0x7f05001a;
        public static final int interstitial_bn=0x7f05001b;
        public static final int leak_canary_analysis_failed=0x7f050000;
        public static final int leak_canary_class_has_leaked=0x7f050001;
        public static final int leak_canary_could_not_save_text=0x7f050002;
        public static final int leak_canary_could_not_save_title=0x7f050003;
        public static final int leak_canary_delete=0x7f050004;
        public static final int leak_canary_delete_all=0x7f050005;
        public static final int leak_canary_delete_all_leaks_title=0x7f050006;
        public static final int leak_canary_display_activity_label=0x7f050007;
        public static final int leak_canary_excluded_row=0x7f050008;
        public static final int leak_canary_failure_report=0x7f050009;
        public static final int leak_canary_leak_excluded=0x7f05000a;
        public static final int leak_canary_leak_list_title=0x7f05000b;
        public static final int leak_canary_no_leak_text=0x7f05000c;
        public static final int leak_canary_no_leak_title=0x7f05000d;
        public static final int leak_canary_notification_channel=0x7f05000e;
        public static final int leak_canary_notification_message=0x7f05000f;
        public static final int leak_canary_permission_not_granted=0x7f050010;
        public static final int leak_canary_permission_notification_text=0x7f050011;
        public static final int leak_canary_permission_notification_title=0x7f050012;
        public static final int leak_canary_share_heap_dump=0x7f050013;
        public static final int leak_canary_share_leak=0x7f050014;
        public static final int leak_canary_share_with=0x7f050015;
        public static final int leak_canary_storage_permission_activity_label=0x7f050016;
        public static final int leak_canary_toast_heap_dump=0x7f050017;
        public static final int load_ad_bn=0x7f05001c;
        public static final int mix_bn=0x7f05001d;
        public static final int native_320X210_group_text_img_bn=0x7f05001e;
        public static final int native_320X210_text_img_bn=0x7f05001f;
        public static final int native_512X512_text_icon_bn=0x7f050020;
        public static final int native_640X320_text_img_bn=0x7f050021;
        public static final int native_bn=0x7f050022;
        public static final int native_templet_320X210_normal_bn=0x7f050023;
        public static final int native_templet_320X210_recycler_bn=0x7f050024;
        public static final int native_templet_640X320_normal_bn=0x7f050025;
        public static final int native_templet_640X320_recycler_bn=0x7f050026;
        public static final int native_templet_ad_height=0x7f050027;
        public static final int native_templet_ad_width=0x7f050028;
        public static final int native_templet_bn=0x7f050029;
        public static final int native_templet_group_320X210_normal_bn=0x7f05002a;
        public static final int native_templet_group_320X210_recycler_bn=0x7f05002b;
        public static final int req_video_bn=0x7f05002c;
        public static final int reward_video_bn=0x7f05002d;
        public static final int show_ad_bn=0x7f05002e;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060001;
        public static final int leak_canary_LeakCanary_Base=0x7f060000;
        public static final int leak_canary_Theme_Transparent=0x7f060002;
    }
    public static final class styleable {
        /** Attributes that can be used with a RecyclerView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #RecyclerView_android_descendantFocusability android:descendantFocusability}</code></td><td></td></tr>
           <tr><td><code>{@link #RecyclerView_android_orientation android:orientation}</code></td><td></td></tr>
           <tr><td><code>{@link #RecyclerView_layoutManager com.oppo.mobaddemo:layoutManager}</code></td><td></td></tr>
           <tr><td><code>{@link #RecyclerView_reverseLayout com.oppo.mobaddemo:reverseLayout}</code></td><td></td></tr>
           <tr><td><code>{@link #RecyclerView_spanCount com.oppo.mobaddemo:spanCount}</code></td><td></td></tr>
           <tr><td><code>{@link #RecyclerView_stackFromEnd com.oppo.mobaddemo:stackFromEnd}</code></td><td></td></tr>
           </table>
           @see #RecyclerView_android_descendantFocusability
           @see #RecyclerView_android_orientation
           @see #RecyclerView_layoutManager
           @see #RecyclerView_reverseLayout
           @see #RecyclerView_spanCount
           @see #RecyclerView_stackFromEnd
         */
        public static final int[] RecyclerView = {
            0x010100c4, 0x010100f1, 0x7f010000, 0x7f010001,
            0x7f010002, 0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#descendantFocusability}
          attribute's value can be found in the {@link #RecyclerView} array.
          @attr name android:descendantFocusability
        */
        public static final int RecyclerView_android_descendantFocusability = 1;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#orientation}
          attribute's value can be found in the {@link #RecyclerView} array.
          @attr name android:orientation
        */
        public static final int RecyclerView_android_orientation = 0;
        /**
          <p>This symbol is the offset where the {@link com.oppo.mobaddemo.R.attr#layoutManager}
          attribute's value can be found in the {@link #RecyclerView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.oppo.mobaddemo:layoutManager
        */
        public static final int RecyclerView_layoutManager = 2;
        /**
          <p>This symbol is the offset where the {@link com.oppo.mobaddemo.R.attr#reverseLayout}
          attribute's value can be found in the {@link #RecyclerView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.oppo.mobaddemo:reverseLayout
        */
        public static final int RecyclerView_reverseLayout = 4;
        /**
          <p>This symbol is the offset where the {@link com.oppo.mobaddemo.R.attr#spanCount}
          attribute's value can be found in the {@link #RecyclerView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.oppo.mobaddemo:spanCount
        */
        public static final int RecyclerView_spanCount = 3;
        /**
          <p>This symbol is the offset where the {@link com.oppo.mobaddemo.R.attr#stackFromEnd}
          attribute's value can be found in the {@link #RecyclerView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.oppo.mobaddemo:stackFromEnd
        */
        public static final int RecyclerView_stackFromEnd = 5;
    };
}
